### ISSUE TITLE
Register `PETSc.jl` as a Julia package

### ISSUE THREAD

**Issue by jkozdon** [JuliaParallel/PETSc.jl#131]
Something we should consider. Not sure if there are downsides to doing it now(?)

**Comment by boriskaus** [comment]
Do you have to tag/push a new version to the registry every time we make a change? 
If yes, it's probably better to wait until the parallel functionality is added (and perhaps the new PETSc_jll files as well) as I expect quite a few changes in the coming days. 
Yet, if you wish feel free to add it already.

**Comment by jkozdon** [comment]
I've been thinking that we might want to go ahead and register this for now. Not sure what's involved with that, but I see no downside and we make sure we have the package name PETSc (not that I think someone else will grab it).

That said, I don't think that I have permissions to do this (since I am not a JuliaParallel member).

Also, one thing I realized is should we change from using `master` to `main` as our primary branch before registering?

**Comment by boriskaus** [comment]
Yes, I agree that renaming to `main` is politically more correct.

I just added another package to the registry (GeoParams.jl) and have one in the pipeline (GeophysicalModelGenerator.jl). The easiest way to add new packages is through your JuliaHub account where you just provide the link to the github repo. New packages have a waiting period of 3 days. I believe that `PETSc.jl` used to be registered at some stage so that might be faster.

**Comment by vchuravy** [comment]
@jkozdon I also added you as a member to JuliaParallel

**Comment by vchuravy** [comment]
I renamed the main branch to main :)

(Also see https://github.com/github/renaming#renaming-existing-branches)

**Comment by jkozdon** [comment]
Thanks @vchuravy
