### ISSUE TITLE
Reuse OpenBLAS installation from Julia distribution

### ISSUE THREAD

**Issue by jiahao** [JuliaParallel/PETSc.jl#16]
Currently, `PETSc.jl` fails to build PETSc on a Linux system without a BLAS package installed at the system level.

Instead, it would be preferable to reuse the OpenBLAS or MKL BLAS installation that comes with Julia, especially if Julia is built from source.

It looks like the relevant `./configure` options are

```
BLAS/LAPACK:
  --with-blas-lib=<libraries: e.g. [/Users/..../libblas.a,...]>
       Indicate the library(s) containing BLAS
  --known-64-bit-blas-indices=<bool>
       Indicate if using 64 bit integer BLAS  current: 0
```

**Comment by jiahao** [comment]
Although it looks like the name mangling we do on 64-bit platforms makes it impossible for PETSc to understand.

For reference, the Ubuntu packages needed are installed by `apt-get install libopenblas-dev liblapack-dev`

**Comment by stevengj** [comment]
@jedbrown, would PETSc be open to a patch to use a BLAS library with mangled names?

In particular, Julia compiles BLAS with a 64-bit integer interface (instead of the default 32-bit integer API), and to avoid conflicts with other BLAS libraries (when libraries using a 32-bit BLAS are loaded) we rename both the the library (to `libopenblas64_.so`) and the symbols (by appending `64_`, e.g. `dgemm64_`).

It would be nice to be able to compile PETSc to use the 64-bit BLAS as well, and similarly to link the mangled symbols.  This looks easy to do, since `petscblaslapack_c.h` already defines macros for all of the BLAS and LAPACK symbols.

**Comment by stevengj** [comment]
(See also xianyi/OpenBLAS#646)

**Comment by jedbrown** [comment]
Yes, we can add this to PETSc.  It'll be a good reason for us to clean up those macros somewhat (because I don't want a combinatorial expansion of that nasty code), but it doesn't look like much effort.  Are your 64-bit conventions common or specific to Julia?

**Comment by stevengj** [comment]
They are specific to Julia.  As far as we can tell, there are no common ABI conventions for the 64-bit BLAS, and the situation is something of a mess.  (See the linked OpenBLAS discussion and also JuliaLang/julia#4923.)

Basically you should support adding an arbitrary suffix/prefix to the BLAS and LAPACK symbols.

**Comment by stevengj** [comment]
Correction: the `64_` suffix is also used by the 64-bit SunPerf BLAS, apparently.

**Comment by nalimilan** [comment]
And now that `64_` suffix is also used by a Fedora/EPEL OpenBLAS package.

**Comment by stevengj** [comment]
I've started a PETSc PR: https://bitbucket.org/petsc/petsc/pull-requests/394
