### ISSUE TITLE
PETSc.PetscError(63,"Argument out of range")

### ISSUE THREAD

**Issue by ahojukka5** [JuliaParallel/PETSc.jl#52]
I'm getting errors "Argument out of range" when trying to populate matrix. Using Ubuntu 14.04 this problem can be reproduced with the following MWE:

```
A = PETSc.Mat(Float64, 30, 30)
for i=1:30
    A[1, i] = 1.0
end
# => PETSc.PetscError(63,"Argument out of range") when i=17
```

If ```A[1,i]``` is changed to ```A[i,1]``` or ```A[i,i]``` everything seems to work. 

[Some others](http://fenicsproject.org/qa/3929/init-a-petsc-matrix) have discovered this problem also.

**Comment by JaredCrean2** [comment]
You'll have to specify the preallocation the matrix.  The default pre-allocation is 16 non zeros per row in the diagonal block of the matrix, which is why the error happens when the loop reaches `i=17`.  The signature of the constructor you call in the example is located here on line 27 of https://github.com/JuliaParallel/PETSc.jl/blob/master/src/mat.jl.  The function  signature is:

```julia
unction Mat{T}(::Type{T}, m::Integer, n::Integer;
                mlocal::Integer=C.PETSC_DECIDE, nlocal::Integer=C.PETSC_DECIDE,
                nz::Integer=16, nnz::AbstractVector=PetscInt[],
                onz::Integer=0, onnz::AbstractVector=PetscInt[],
                comm::MPI.Comm=MPI.COMM_WORLD,
                mtype::Symbol=C.MATMPIAIJ)
```

you can set `nz` to whatever value you want (30 in your example).

Please write back if this solves your problem so we can close the issue.

**Comment by ahojukka5** [comment]
Yes, I confirm that using ```;nz=30``` the error vanishes.

**Comment by buggaero** [comment]
That line number is not 27 but starts right after 67.
